import type { CategoryEntity } from './types'

export const categories: CategoryEntity[] = [
  { id: 'food', type: 'expense', name: '餐饮', icon: '🍽️', order: 1 },
  { id: 'daily', type: 'expense', name: '生活用品', icon: '🏪', order: 2 },
  { id: 'shopping', type: 'expense', name: '购物', icon: '🛍️', order: 3 },
  { id: 'accommodation', type: 'expense', name: '住宿', icon: '🏠', order: 4 },
  { id: 'everyday', type: 'expense', name: '日常', icon: '📦', order: 5 },
  { id: 'study', type: 'expense', name: '学习', icon: '📚', order: 6 },
  { id: 'social', type: 'expense', name: '人情', icon: '💗', order: 7 },
  { id: 'entertainment', type: 'expense', name: '娱乐', icon: '🎡', order: 8 },
  { id: 'beauty', type: 'expense', name: '美妆', icon: '💄', order: 9 },
  { id: 'travel', type: 'expense', name: '旅游', icon: '🎫', order: 10 },
  { id: 'health', type: 'expense', name: '医疗', icon: '🏥', order: 11 },
  { id: 'membership', type: 'expense', name: '会员租用', icon: '👑', order: 12 },
  { id: 'communication', type: 'expense', name: '通讯', icon: '📱', order: 13 },
  { id: 'electronics', type: 'expense', name: '电子产品', icon: '🎧', order: 14 },
  { id: 'transport', type: 'expense', name: '交通', icon: '🚕', order: 15 },
  { id: 'food-breakfast', parentId: 'food', type: 'expense', name: '早餐', icon: '🥪', order: 1 },
  { id: 'food-lunch', parentId: 'food', type: 'expense', name: '午餐', icon: '🍱', order: 2 },
  { id: 'food-dinner', parentId: 'food', type: 'expense', name: '晚餐', icon: '🍲', order: 3 },
  { id: 'food-drink', parentId: 'food', type: 'expense', name: '奶茶咖啡', icon: '☕', order: 4 },
  { id: 'food-snack', parentId: 'food', type: 'expense', name: '零食', icon: '🍪', order: 5 },
  { id: 'daily-cleaning', parentId: 'daily', type: 'expense', name: '清洁用品', icon: '🧹', order: 1 },
  { id: 'daily-kitchen', parentId: 'daily', type: 'expense', name: '厨具', icon: '🍳', order: 2 },
  { id: 'daily-textile', parentId: 'daily', type: 'expense', name: '家纺', icon: '🛏️', order: 3 },
  { id: 'daily-hygiene', parentId: 'daily', type: 'expense', name: '卫生用品', icon: '🧻', order: 4 },
  { id: 'shopping-clothes', parentId: 'shopping', type: 'expense', name: '服饰', icon: '👕', order: 1 },
  { id: 'shopping-bag', parentId: 'shopping', type: 'expense', name: '鞋包', icon: '👜', order: 2 },
  { id: 'shopping-digital', parentId: 'shopping', type: 'expense', name: '数码', icon: '⌚', order: 3 },
  { id: 'shopping-appliance', parentId: 'shopping', type: 'expense', name: '家电', icon: '🔌', order: 4 },
  { id: 'accommodation-rent', parentId: 'accommodation', type: 'expense', name: '房租', icon: '🔑', order: 1 },
  { id: 'accommodation-property', parentId: 'accommodation', type: 'expense', name: '物业', icon: '🏢', order: 2 },
  { id: 'accommodation-utilities', parentId: 'accommodation', type: 'expense', name: '水电燃气', icon: '💡', order: 3 },
  { id: 'accommodation-repair', parentId: 'accommodation', type: 'expense', name: '家居维修', icon: '🛠️', order: 4 },
  { id: 'everyday-delivery', parentId: 'everyday', type: 'expense', name: '快递', icon: '📮', order: 1 },
  { id: 'everyday-print', parentId: 'everyday', type: 'expense', name: '打印复印', icon: '🖨️', order: 2 },
  { id: 'everyday-fee', parentId: 'everyday', type: 'expense', name: '日常杂费', icon: '🧾', order: 3 },
  { id: 'study-books', parentId: 'study', type: 'expense', name: '书籍', icon: '📖', order: 1 },
  { id: 'study-course', parentId: 'study', type: 'expense', name: '课程', icon: '🎓', order: 2 },
  { id: 'study-exam', parentId: 'study', type: 'expense', name: '考试', icon: '📝', order: 3 },
  { id: 'study-stationery', parentId: 'study', type: 'expense', name: '文具', icon: '✏️', order: 4 },
  { id: 'social-redpacket', parentId: 'social', type: 'expense', name: '红包', icon: '🧧', order: 1 },
  { id: 'social-gift', parentId: 'social', type: 'expense', name: '礼物', icon: '🎁', order: 2 },
  { id: 'social-treat', parentId: 'social', type: 'expense', name: '请客', icon: '🥂', order: 3 },
  { id: 'social-family', parentId: 'social', type: 'expense', name: '孝敬长辈', icon: '❤️', order: 4 },
  { id: 'entertainment-movie', parentId: 'entertainment', type: 'expense', name: '电影', icon: '🎬', order: 1 },
  { id: 'entertainment-game', parentId: 'entertainment', type: 'expense', name: '游戏', icon: '🎮', order: 2 },
  { id: 'entertainment-sport', parentId: 'entertainment', type: 'expense', name: '运动', icon: '🏸', order: 3 },
  { id: 'entertainment-ktv', parentId: 'entertainment', type: 'expense', name: 'KTV', icon: '🎤', order: 4 },
  { id: 'beauty-skincare', parentId: 'beauty', type: 'expense', name: '护肤', icon: '🧴', order: 1 },
  { id: 'beauty-makeup', parentId: 'beauty', type: 'expense', name: '彩妆', icon: '💋', order: 2 },
  { id: 'beauty-hair', parentId: 'beauty', type: 'expense', name: '美发', icon: '💇', order: 3 },
  { id: 'beauty-salon', parentId: 'beauty', type: 'expense', name: '美容', icon: '🧖', order: 4 },
  { id: 'travel-ticket', parentId: 'travel', type: 'expense', name: '景点门票', icon: '🎟️', order: 1 },
  { id: 'travel-hotel', parentId: 'travel', type: 'expense', name: '酒店', icon: '🏨', order: 2 },
  { id: 'travel-flight', parentId: 'travel', type: 'expense', name: '机票车票', icon: '✈️', order: 3 },
  { id: 'travel-food', parentId: 'travel', type: 'expense', name: '旅行餐饮', icon: '🍜', order: 4 },
  { id: 'health-doctor', parentId: 'health', type: 'expense', name: '看病', icon: '🩺', order: 1 },
  { id: 'health-medicine', parentId: 'health', type: 'expense', name: '买药', icon: '💊', order: 2 },
  { id: 'health-checkup', parentId: 'health', type: 'expense', name: '体检', icon: '📋', order: 3 },
  { id: 'health-dental', parentId: 'health', type: 'expense', name: '牙科', icon: '🦷', order: 4 },
  { id: 'membership-video', parentId: 'membership', type: 'expense', name: '视频会员', icon: '📺', order: 1 },
  { id: 'membership-music', parentId: 'membership', type: 'expense', name: '音乐会员', icon: '🎵', order: 2 },
  { id: 'membership-software', parentId: 'membership', type: 'expense', name: '软件订阅', icon: '💻', order: 3 },
  { id: 'membership-cloud', parentId: 'membership', type: 'expense', name: '网盘云服务', icon: '☁️', order: 4 },
  { id: 'communication-phone', parentId: 'communication', type: 'expense', name: '手机话费', icon: '☎️', order: 1 },
  { id: 'communication-broadband', parentId: 'communication', type: 'expense', name: '宽带', icon: '📡', order: 2 },
  { id: 'communication-data', parentId: 'communication', type: 'expense', name: '流量套餐', icon: '📶', order: 3 },
  { id: 'communication-mail', parentId: 'communication', type: 'expense', name: '邮寄', icon: '📦', order: 4 },
  { id: 'electronics-phone', parentId: 'electronics', type: 'expense', name: '手机', icon: '📱', order: 1 },
  { id: 'electronics-computer', parentId: 'electronics', type: 'expense', name: '电脑', icon: '💻', order: 2 },
  { id: 'electronics-accessory', parentId: 'electronics', type: 'expense', name: '配件', icon: '🎧', order: 3 },
  { id: 'electronics-repair', parentId: 'electronics', type: 'expense', name: '维修', icon: '🔧', order: 4 },
  { id: 'transport-bus', parentId: 'transport', type: 'expense', name: '公交', icon: '🚌', order: 1 },
  { id: 'transport-subway', parentId: 'transport', type: 'expense', name: '地铁', icon: '🚇', order: 2 },
  { id: 'transport-taxi', parentId: 'transport', type: 'expense', name: '打车', icon: '🚕', order: 3 },
  { id: 'transport-fuel', parentId: 'transport', type: 'expense', name: '加油充电', icon: '⛽', order: 4 },
  { id: 'transport-parking', parentId: 'transport', type: 'expense', name: '停车', icon: '🅿️', order: 5 },
  { id: 'home', type: 'income', name: '家用', icon: '🐖', order: 1 },
  { id: 'salary', type: 'income', name: '工资', icon: '💳', order: 2 },
  { id: 'gift', type: 'income', name: '红包', icon: '🧧', order: 3 },
  { id: 'rent', type: 'income', name: '租金', icon: '🏠', order: 4 },
  { id: 'bonus', type: 'income', name: '奖金', icon: '💰', order: 5 },
  { id: 'invest', type: 'income', name: '理财', icon: '📊', order: 6 },
  { id: 'home-transfer', parentId: 'home', type: 'income', name: '家庭转账', icon: '👪', order: 1 },
  { id: 'home-living', parentId: 'home', type: 'income', name: '生活费', icon: '🏡', order: 2 },
  { id: 'salary-base', parentId: 'salary', type: 'income', name: '基本工资', icon: '💳', order: 1 },
  { id: 'salary-allowance', parentId: 'salary', type: 'income', name: '补贴', icon: '🪙', order: 2 },
  { id: 'gift-festival', parentId: 'gift', type: 'income', name: '节日红包', icon: '🧧', order: 1 },
  { id: 'gift-friend', parentId: 'gift', type: 'income', name: '亲友赠予', icon: '🎁', order: 2 },
  { id: 'rent-income', parentId: 'rent', type: 'income', name: '房租收入', icon: '🏠', order: 1 },
  { id: 'rent-deposit', parentId: 'rent', type: 'income', name: '押金返还', icon: '🔑', order: 2 },
  { id: 'bonus-performance', parentId: 'bonus', type: 'income', name: '绩效奖金', icon: '🏅', order: 1 },
  { id: 'bonus-year', parentId: 'bonus', type: 'income', name: '年终奖', icon: '🎉', order: 2 },
  { id: 'invest-interest', parentId: 'invest', type: 'income', name: '利息', icon: '🪙', order: 1 },
  { id: 'invest-dividend', parentId: 'invest', type: 'income', name: '分红', icon: '📈', order: 2 },
  { id: 'invest-redeem', parentId: 'invest', type: 'income', name: '理财赎回', icon: '💰', order: 3 },
]
